print("Welcome to Aom phone for free")
print("กรอกชื่อ-นามสกุล ที่อยู่ เบอร์โทรศัพท์ แจ้งวันที่ต้องการเช่า")
Name = input("ชื่อ")
lastname = input("นามสกุล")
Address = input("ที่อยู่")
Phonenumber = input("เบอร์โทรศัพท์")
Date = input ("วันที่ต้องการเช่า")
print("thank you")
print("คุณ" , Name , lastname , "อยู่ที่", Address , "เบอร์โทรศัพท์" , Phonenumber ,"วันที่ต้องการเช่า" , Date)